title: <p align="center"> VINAY KUMAR BOLLU </p>
logo: /assets/img/logo.png
description: 
<p align="center">
<br>
Offering over 5 years of challenging & incredibly rewarding career in Application Software development in fast-paced industry
Highly creative mind in preparing technical documents and providing timelines for projects.
<br>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
